<footer id="footer">
         <div class="content">

            <div class="copyright">
               <p>©2014 <?php include ($_SERVER['DOCUMENT_ROOT']. "/assets/includes/website-name.inc"); ?>. All rights reserved.</p>
               <div class="websiteBy">
                  <a href="http://www.loaidesign.co.uk" target="_blank">
                     <abbr title="Want a Website as Good as This? Click Here!">Website by<img alt="Loai Design Studio" src="assets/elements/loai-design-studio-logo.png"></abbr>
                  </a>
                  <br><br>
                  <a id="removeStyle">View Desktop Site</a>
               </div>
            </div>

            <nav class="links">
               <ul>
                  <?php include ($_SERVER['DOCUMENT_ROOT']. "/assets/includes/menu.inc"); ?>
               </ul>
            </nav>

            <div class="socialbar">
               <?php include ($_SERVER['DOCUMENT_ROOT']. "/assets/includes/social-media-icons.inc"); ?>
            </div>

         </div>
      </footer>