
   <link rel="shortcut icon" href="assets/elements/favicon.ico">
   <link rel="stylesheet" type="text/css" href="assets/css/reset.css">
   <link rel="stylesheet" type="text/css" href="assets/css/core.css">
   <link rel="stylesheet" id="mobileSheet" media="screen and (max-width: 1024px)" href="assets/css/tablet-and-mobile.css"/>
   <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.css"/>

   <!--Libraries-->
   <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

   <!--Functions-->
   <?php include "assets/includes/functions.inc"; ?>

   <!--IE Support-->
   <!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

   <!--Analytics-->