<li><a <?php href('index.php'); ?>>Home</a></li>
            <li><a <?php href('about.php'); ?>>About</a></li>
            <li><a <?php href('press.php'); ?>>News &amp; Press</a></li>
            <li class="subMenu"><a class="noLink">Clients</a>
               <ul>
                  <li><a <?php href('references.php'); ?>>References</a></li>
                  <li><a <?php href('comments.php'); ?>>Comments</a></li>
               </ul>
            </li>
            <li class="subMenu"><a class="noLink">Scent Solutions</a>
               <ul>
                  <li><a <?php href('services.php'); ?>>Services</a></li>
                  <li><a <?php href('fragrances.php'); ?>>Fragrances</a></li>
                  <li><a <?php href('scent-systems.php'); ?>>Scent Systems</a></li>
                  <li><a <?php href('scent-facts.php'); ?>>Scent Facts</a></li>
               </ul>
            </li>
            <li class="subMenu"><a class="noLink">Contact</a>
               <ul>
                  <li><a <?php href('contact.php'); ?>>Ghana</a></li>
                  <li><a <?php href('become-partner.php'); ?>>Become a Partner</a></li>
                  <li><a <?php href('international.php'); ?>>International</a></li>
               </ul>
            </li>