<div class="socialbar">
   <abbr title="Facebook"><a class="icon-facebook" href="https://www.facebook.com/pages/Scentlinqgh/864535526919671" target="_blank"></a></abbr>
   <abbr title="Twitter"><a class="icon-twitter" href="https://twitter.com/scentlinqgh" target="_blank"></a></abbr>
<!--    <abbr title="Google+"><a class="icon-google" href="https://plus.google.com/112359040714698332143/posts" target="_blank"></a></abbr> -->
</div>